modLoader = "kotlinforforge"
loaderVersion = "[3,)"
license = "MIT"

issueTrackerURL = "https://github.com/Talia-12/MoreIotas/issues"

[[mods]]
modId = "moreiotas"
version = "${file.jarVersion}"
displayName = "MoreIotas"
displayURL = "https://github.com/Talia-12/MoreIotas"
logoFile = "logo.png"
credits = "petrak@ and other developers of Hex Casting for the mod that this is an addon for."
authors = "Talia"
description = ""

[[dependencies.moreiotas]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moreiotas]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moreiotas]]
modId = "paucal"
mandatory = true
versionRange = "[0.5.0,0.6.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moreiotas]]
modId = "patchouli"
mandatory = true
versionRange = "[1.19.2-77,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moreiotas]]
modId = "hexcasting"
mandatory = true
versionRange = "[1.0-pre-449,)"
ordering = "NONE"
side = "BOTH"
